### ISSUE TITLE
There is no a repo here

### ISSUE THREAD

**Issue by JrogeT** [Sistemas-de-info/documentMan-server#1]
Why?

**Comment by pablotardio** [comment]
Because we are structuring the express project, we prefer not to use a generator, or maybe, we are thinking about it

**Comment by pablotardio** [comment]
> Why?
Because we are structuring the express project, we prefer not to use a generator, or maybe, we are thinking about it

**Comment by pablotardio** [comment]
> Why?

Because we are structuring the express project, we prefer not to use a generator, or maybe, we are thinking about it

**Comment by JrogeT** [comment]
Are you going to use Node?
